### ISSUE TITLE
Angle transformation

### ISSUE THREAD

**Issue by DuckyDiyy** [wzqvip/FAB_Academy_StarTracker#1]
if (Xin <= 180 and Xin >= 0){ X = 180 - Xin; Y = 180 - Yin;}
  else if(Xin <= 360){ X = 360 - Xin; Y = Yin;}

**Comment by wzqvip** [comment]
Solved.

`bool servo_driver(int Xin, int Yin) {  // Function to drive the servos
    if (Xin <= 180 and Xin >= 0) {
        int xTemp = 180 - Xin;
        if (abs(xTemp - servoX.read()) > 5) {
            X = xTemp;
        }
        int yTemp = 180 - Yin;
        if (abs(yTemp - servoY.read()) > 5) {
            Y = yTemp;
        }
    } else if (Xin <= 360) {
        int xTemp = 360 - Xin;
        if (abs(xTemp - servoX.read()) > 5) {
            X = xTemp;
        }
        int yTemp = Yin;
        if (abs(yTemp - servoY.read()) > 5) {
            Y = yTemp;
        }
    } else {
        X = 0;
        Y = 0;
        return false;
    }
    if (Y > 180) {
        Y = 180;
    } else if (Y < 0) {
        Y = 0;
    }
    servoX.write(X);
    servoY.write(Y);
    return true;
}`
